addSbtPlugin("com.eed3si9n"     % "sbt-assembly"              % "0.15.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph"      % "0.10.0-RC1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check"      % "3.0.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.5.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-eviction-rules"        % "1.0.0-RC1")
