name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to our project! Thank you for opening an issue. We appreciate your contribution. Please provide all the necessary details, and our team will review it shortly"
          pr-message: "Hello! Thank you for your pull request. We're excited to review your changes and collaborate with you. Please ensure that you've followed our contribution guidelines and provided a clear description. We look forward to your contribution!"

