name: Release

on:
  push:
    tags:
      - "*"  # Runs when pushing a tag like 1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List downloaded artifact files
        run: ls -R artifacts/

      - name: Download igrafx-udfs-artifact
        uses: actions/download-artifact@v4
        with:
          name: igrafx-udfs-artifact
          path: artifacts/udfs

      - name: Download igrafx-connectors-artifacts
        uses: actions/download-artifact@v4
        with:
          name: igrafx-connectors-artifacts
          path: artifacts/connectors

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload igrafx-udfs-artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/udfs/igrafx-udfs-artifact.zip  # Replace with actual file name
          asset_name: your-udfs-file.zip  # Replace with actual file name
          asset_content_type: application/zip

      - name: Upload igrafx-connectors-artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/connectors/igrafx-connectors-artifact.zip  # Replace with actual file name
          asset_name: your-connectors-file.zip  # Replace with actual file name
          asset_content_type: application/zip
